name: Calculator CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test-job:
    name: Run Calculator Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit and integration tests
        run: npm test
      
      - name: Test summary
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "Calculator tests completed" >> $GITHUB_STEP_SUMMARY

  build-job:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test-job
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: |
          echo "Building Docker image with commit SHA: ${{ github.sha }}"
          docker build -t calculator-devops:${{ github.sha }} .
          docker build -t calculator-devops:latest .
      
      - name: List Docker images
        run: docker images | grep calculator-devops
      
      - name: Test Docker image
        run: |
          echo "Starting container for testing..."
          docker run -d -p 3000:3000 --name calculator-test calculator-devops:latest
          sleep 5
          
          echo "Testing health endpoint..."
          curl -f http://localhost:3000/health || exit 1
          
          echo "Testing calculator API..."
          curl -f -X POST http://localhost:3000/calculate \
            -H "Content-Type: application/json" \
            -d '{"operation":"add","num1":5,"num2":3}' || exit 1
          
          docker stop calculator-test
          docker rm calculator-test
      
      - name: Build summary
        if: always()
        run: |
          echo "## Docker Build Results" >> $GITHUB_STEP_SUMMARY
          echo "Docker image built successfully" >> $GITHUB_STEP_SUMMARY
          echo "Container health check passed" >> $GITHUB_STEP_SUMMARY
          echo "API endpoint verified" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image Tags:**" >> $GITHUB_STEP_SUMMARY
          echo "- calculator-devops:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- calculator-devops:latest" >> $GITHUB_STEP_SUMMARY